dev/4/flask_app/my_app/product/models/category.py
from my_app import db

from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired


class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    products = db.relationship('Product', backref='category', lazy='select')

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '<Category %r>' % (self.name)


class CategoryForm(FlaskForm):
    name = StringField('Nombre: ', validators=[InputRequired()])

dev/4/flask_app/my_app/product/models/product.py
from my_app import db

from decimal import Decimal

from flask_wtf import FlaskForm
from wtforms import StringField, DecimalField, SelectField
from wtforms.validators import InputRequired, NumberRange


class Product(db.Model):
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    price = db.Column(db.Float)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'), nullable=False)

    def __init__(self, name, price, category_id):
        self.name = name
        self.price = price
        self.category_id = category_id

    def __repr__(self):
        return '<Product %r>' % (self.name)


class ProductForm(FlaskForm):
    name = StringField('Nombre: ', validators=[InputRequired()])
    price = DecimalField('Precio: ', validators=[InputRequired(), NumberRange(min=Decimal('0.0'))])
    category_id = SelectField('Categoria: ', coerce=int)

dev/4/flask_app/my_app/product/models/products.py
PRODUCTS = {
    1: {
        'name': 'iPhone 11',
        'category': 'Phones',
        'price': 1005,
    },
    2: {
        'name': 'Pixel',
        'category': 'Phones',
        'price': 700,
    },
    3: {
        'name': 'Mx Master 3',
        'category': 'Mouse',
        'price': 100,
    },
    4: {
        'name': 'iPhone 5',
        'category': 'Phones',
        'price': None,
    },
}

dev/4/flask_app/my_app/__init__.py
from flask import Flask, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user, logout_user
from functools import wraps

from flask_cors import CORS

app = Flask(__name__)

app.config.from_object('configuration.DevelopmentConfig')
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.init_app(app)

login_manager.login_view = "fauth.login"

#cors

cors = CORS(app, resources={r"/api/*":{"origins":"http://localhost:8080"}})

#cors


def rol_admin_need(f):
    @wraps(f)
    def wrapper(*args, **kwds):
        if current_user.rol.value != 'Administrador':
            logout_user()
            return redirect(url_for('fauth.login'))
            # login_manager.unauthorized()
            # return "Tu debes de ser administrador",403
            # print('Llamando a la funcion del decorador '+str(current_user.rol.value))
        return f(*args, **kwds)
    return wrapper

from my_app.product.product import product
from my_app.fauth.views import fauth
from my_app.auth.views import auth
from my_app.product.category import category

#rest
from my_app.rest_api.product_api import product_view
from my_app.rest_api.category_api import category_view

#general
import my_app.general.error_handle

# importar las vistas
app.register_blueprint(product)
app.register_blueprint(category)
# app.register_blueprint(auth)
app.register_blueprint(fauth)

with app.app_context():
    db.create_all()


@app.template_filter('myDouble')
def myDouble_filter(n):
    return n*2

dev/4/flask_app/my_app/fauth/views.py
from my_app import db
from flask import Blueprint, session, render_template, request, redirect, url_for, flash, get_flashed_messages
from my_app.auth.model.user import User, LoginForm, RegisterForm
from flask_login import current_user, login_user, logout_user, login_required
from my_app import login_manager

fauth = Blueprint('fauth', __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@fauth.route('/register', methods=('GET', 'POST'))
def register():

    form = RegisterForm(meta={'csrf': False})

    if form.validate_on_submit():

        if User.query.filter_by(username=form.username.data).first():
            flash("El usuario ya existe en el sistema", 'danger')
        else:
            # Crear un registro
            p = User(form.username.data, form.password.data)
            db.session.add(p)
            db.session.commit()
            flash("Usuario creado con exito")
            return redirect(url_for('fauth.register'))

    if form.errors:
        flash(form.errors, 'danger')

    return render_template('auth/register.html', form=form)


@fauth.route('/login', methods=('GET', 'POST'))
def login():

    if current_user.is_authenticated:
        flash(" Ya esta autenticado")
        return redirect(url_for('product.index'))

    form = LoginForm(meta={'csrf': False})

    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash("Bienvenido de nuevo "+user.username)

            next = request.form['next']
            # is_safe_url should check if the url is safe for redirects.
            # See http://flask.pocoo.org/snippets/62/ for an example.
            # if not is_safe_url(next):
            # return flask.abort(400)

            return redirect(next or url_for('product.index'))

        else:
            flash("Usuario y/o contraseña incorrectos", 'danger')

    if form.errors:
        flash(form.errors, 'danger')

    return render_template('auth/login.html', form=form)


@fauth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('fauth.login'))


@fauth.route('/protegido')
@login_required
def protegido():
    return "Vista protegida"

dev/4/flask_app/my_app/templates/category/_form.html
        {{ form.name.label }} 
        {{ form.name(class="form-control mb-3") }}

dev/4/flask_app/my_app/templates/category/create.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('category.create') }}" method="POST">
        {%include 'category/_form.html'%}

        <input class="btn btn-success" type="submit" value="Enviar">
    </form>

{% endblock %}

dev/4/flask_app/my_app/templates/category/filter.html
<h3>{{ product['name'] }}</h3>

<p>{{ product['category'] }}</p>
<p>${{ product['price'] }}</p>

<? filtro default: para imprmir un menaje cuando el valor es nulo?>
<p>Filtro default:{{ product['price'] | default('sin precio', True) }}</p>

<? filtro safe saca el codigo html para que se rederice correctamente?>
<p>Filtro safe:{{"<h1>Hola mundo</h1>" | safe }}</p>

<? filtro truncate va a cortar el texto seleccionado se reserva 3 caracteres para los ...?>
<p>Filtro truncate: {{"esta es la decroipcion de un producto bastante bueno" | truncate(5) }}</p>

<?Filtro count te cuenta el numero de caracteres que se encuentran en el string?>
<p>Filtro count: {{"esta es la decroipcion de un producto bastante bueno" | count }}</p>

<?Filtro float es para convertir cualquier dato a un dato float?>
<p>Filtro float: {{"70.5" | float }}</p>

<?Filtro int es para convertir cualquier dato a un dato int?>
<p>Filtro int: {{"70.5" | int }}</p>

<?Filtro round es para definior cuantos caracteres quieren que se muestren despues del punto decimal?>
<p>Filtro round: {{ 3.141592653 | round(1) }}</p>

<?Filtro join es para convertir un array en texto?>
<p>Filtro array: {{ ["iPhone", "iPad"] | join(" ,") }}</p>

<?Filtro lengt es para contar la catidad de elementos en un arreglo?>
<p>Filtro length: {{ ["iPhone", "iPad"] | length }}</p>

<?Filtro json es para convertir objetos en json?>
<p>Filtro json: {{ {'offer':False, 'price':50.5, 'k':45} | tojson }}</p>

<p>Filtro global custom: {{ 50 | myDouble}}</p>

<p>Filtro local custom: {{ product | iva }}</p>

dev/4/flask_app/my_app/templates/category/index.html
{% extends 'layout/base.html' %}
{% from 'macro/_pagination.html' import m_pagination %}

{% block container %}

<a class="btn btn-primary mt-2 mb-2" href="{{url_for('category.create')}}"><i class="fa fa-plus"></i>Crear</a>
<br>
<div class="list-category">
  {% for category in categories.items %}
  <div class="card  {{ loop.cycle('odd', 'even') }} mt-3">
    <div class="card-body jumbotron pb-2 pt-3">
      <h3>
        <a href="{{ url_for('category.show', id=category['id']) }}">
          {{ category['name'] }}
        </a>
      </h3>

      <a data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Editar" class="btn btn-success btn-sm" href="{{ url_for('category.update', id=category['id']) }}"><i class="fa fa-edit"></i></a>

      <button data-bs-toggle="modal" data-bs-target="#deleteModal" data-bs-name="{{category['name']}}" data-bs-id="{{category['id']}}"
        class="btn btn-danger btn-sm" href="{{ url_for('category.delete', id=category['id']) }}"><i data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Eliminar producto {{ category['name'] }}" class="fa fa-trash"></i></button>
    </div>
  </div>
  {%endfor%}
</div>

<br>

{{ m_pagination(categories) }}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Borrar: <span></span></h5>
        <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ¿Seguro que desea borrar el registro seleccionado?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <a href="#" id="deleteProduct" class="btn btn-danger">Borrar</a>
      </div>
    </div>
  </div>
</div>
<script>
  window.onload = function () {

    var modal =document.getElementById("deleteModal")

    modal.addEventListener('show.bs.modal', function (event) {

      var button = event.relatedTarget
      var name = button.getAttribute("data-bs-name")
      var id = button.getAttribute("data-bs-id")

      modal.querySelector(".modal-title span").innerHTML=name
      modal.querySelector("#deleteProduct").setAttribute("href","/category-delete/"+id)


    })
  }
</script>

{% endblock %}

dev/4/flask_app/my_app/templates/category/show.html
{% extends 'layout/base.html' %}

{% block container %}
    <h3>{{ product['name'] }}</h3>

    <p>{{ product['category'] }}</p>
    <p>${{ product['price'] }}</p>

    {% if product['price']>1000 %}
    <p>Precio regular</p> 
    {% else %}
    <p>Precio oferta</p>
    {% endif %}

{% endblock %}

dev/4/flask_app/my_app/templates/category/update.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('category.update',id=category.id) }}" method="POST">
        {%include 'category/_form.html'%}

        <input class="btn btn-success" type="submit" value="Actualizar">
    </form>

{% endblock %}

dev/4/flask_app/my_app/templates/fragment/_alert.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
    {% endif %}
{% endwith %}

dev/4/flask_app/my_app/templates/fragment/_footer.html
<footer class="bg-dark text-center text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgb(207, 205, 205);">
      © 2020 Copyright:
      <a class="text-dark" href="#">Flask</a>
    </div>
    <!-- Copyright -->
  </footer>

dev/4/flask_app/my_app/templates/fragment/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Flask</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if current_user.username %}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('product.index')}}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              CRUD
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{{url_for('product.index')}}">Productos</a></li>
              <li><a class="dropdown-item" href="{{url_for('category.index')}}">Categorias</a></li>
            </ul>
          </li>
          {% endif %}
        </ul>

        <ul class="navbar-nav mb-2 mb-lg-0">

          {% if current_user.username %}
          
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('fauth.login')}}">Login</a>
          </li>
          {% endif %}
          


          
          

          {% if current_user.username %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Hola: {{ current_user.username }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Perfil</a></li>
              <li><a class="dropdown-item" href="{{url_for('fauth.logout')}}">Logout</a></li>
            </ul>
          </li>
          {% endif %}

          
        </ul>

      </div>
    </div>
  </nav>

dev/4/flask_app/my_app/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='fontawesome/css/all.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='product/css/style.custom.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='global/css/style.custom.css')}}">


    <title>CRUD</title>
</head>

<body>
    {% include 'fragment/_nav.html' %}

    <div class="container">
        {% include 'fragment/_alert.html' %}
        {% block container %}
        {% endblock %}
    </div>
    <br>
    {% include 'fragment/_footer.html' %}
    <script src="{{url_for('static', filename='global/js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='product/js/main.js')}}"></script>

</body>

</html>

dev/4/flask_app/my_app/templates/macro/_pagination.html
{% macro m_pagination(pagination) %}

<nav aria-label="Page navigation example">
    <ul class="pagination">

        {% if pagination.has_prev %}
            <li class="page-item"><a class="page-link" href="{{ url_for('product.index', page=pagination.prev_num) }}">&laquo;</a></li>
        {% endif %}

        {%- for page in pagination.iter_pages() %}  

        {% if page != pagination.page %}
            <li class="page-item"><a class="page-link" href="{{ url_for('product.index', page=page) }}">{{ page }}</a></li>
        {% else %}
            <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page }}</a>
            </li>
        {% endif %}
        {%- endfor %}

        {% if pagination.has_next %}
        <li class="page-item"><a class="page-link" href="{{ url_for('product.index', page=pagination.next_num) }}">&raquo;</a></li>
        {% endif %}

    </ul>
</nav>

{%- endmacro %}

dev/4/flask_app/my_app/templates/product/_form.html
        {{ form.name.label }} 
        {{ form.name(class="form-control mb-3") }}

        {{ form.price.label }} 
        {{ form.price(class="form-control mb-3") }} 

        {{ form.category_id.label }} 
        {{ form.category_id(class="form-control mb-3") }}

dev/4/flask_app/my_app/templates/product/create.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.create') }}" method="POST">
        {%include 'product/_form.html'%}

        <input class="btn btn-success" type="submit" value="Enviar">
    </form>

{% endblock %}

dev/4/flask_app/my_app/templates/product/filter.html
<h3>{{ product['name'] }}</h3>

<p>{{ product['category'] }}</p>
<p>${{ product['price'] }}</p>

<? filtro default: para imprmir un menaje cuando el valor es nulo?>
<p>Filtro default:{{ product['price'] | default('sin precio', True) }}</p>

<? filtro safe saca el codigo html para que se rederice correctamente?>
<p>Filtro safe:{{"<h1>Hola mundo</h1>" | safe }}</p>

<? filtro truncate va a cortar el texto seleccionado se reserva 3 caracteres para los ...?>
<p>Filtro truncate: {{"esta es la decroipcion de un producto bastante bueno" | truncate(5) }}</p>

<?Filtro count te cuenta el numero de caracteres que se encuentran en el string?>
<p>Filtro count: {{"esta es la decroipcion de un producto bastante bueno" | count }}</p>

<?Filtro float es para convertir cualquier dato a un dato float?>
<p>Filtro float: {{"70.5" | float }}</p>

<?Filtro int es para convertir cualquier dato a un dato int?>
<p>Filtro int: {{"70.5" | int }}</p>

<?Filtro round es para definior cuantos caracteres quieren que se muestren despues del punto decimal?>
<p>Filtro round: {{ 3.141592653 | round(1) }}</p>

<?Filtro join es para convertir un array en texto?>
<p>Filtro array: {{ ["iPhone", "iPad"] | join(" ,") }}</p>

<?Filtro lengt es para contar la catidad de elementos en un arreglo?>
<p>Filtro length: {{ ["iPhone", "iPad"] | length }}</p>

<?Filtro json es para convertir objetos en json?>
<p>Filtro json: {{ {'offer':False, 'price':50.5, 'k':45} | tojson }}</p>

<p>Filtro global custom: {{ 50 | myDouble}}</p>

<p>Filtro local custom: {{ product | iva }}</p>

dev/4/flask_app/my_app/templates/product/index.html
{% extends 'layout/base.html' %}
{% from 'macro/_pagination.html' import m_pagination %}

{% block container %}

<a class="btn btn-primary mt-2 mb-2" href="{{url_for('product.create')}}"><i class="fa fa-plus"></i>Crear</a>
<br>
<div class="list-product">
  {% for product in products %}
  <div class="card  {{ loop.cycle('odd', 'even') }} mt-3">
    <div class="card-body jumbotron pb-2 pt-3">
      <h3>
        <a href="{{ url_for('product.show', id=product['id']) }}">
          {{ product['name'] }}
        </a>
      </h3>

      <h5>{{ product['category'].name }}</h5>

      <a data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Editar" class="btn btn-success btn-sm" href="{{ url_for('product.update', id=product['id']) }}"><i class="fa fa-edit"></i></a>

      <button data-bs-toggle="modal" data-bs-target="#deleteModal" data-bs-name="{{product['name']}}" data-bs-id="{{product['id']}}"
        class="btn btn-danger btn-sm" href="{{ url_for('product.delete', id=product['id']) }}"><i data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Eliminar producto {{ product['name'] }}" class="fa fa-trash"></i></button>
    </div>
  </div>
  {%endfor%}
</div>

<br>

{{ m_pagination(products) }}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Borrar: <span></span></h5>
        <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ¿Seguro que desea borrar el registro seleccionado?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <a href="#" id="deleteProduct" class="btn btn-danger">Borrar</a>
      </div>
    </div>
  </div>
</div>
<script>
  window.onload = function () {

    var modal =document.getElementById("deleteModal")

    modal.addEventListener('show.bs.modal', function (event) {

      var button = event.relatedTarget
      var name = button.getAttribute("data-bs-name")
      var id = button.getAttribute("data-bs-id")

      modal.querySelector(".modal-title span").innerHTML=name
      modal.querySelector("#deleteProduct").setAttribute("href","/product-delete/"+id)


    })
  }
</script>

{% endblock %}

dev/4/flask_app/my_app/templates/product/show.html
{% extends 'layout/base.html' %}

{% block container %}
    <h3>{{ product['name'] }}</h3>

    <p>{{ product['category'] }}</p>
    <p>${{ product['price'] }}</p>

    {% if product['price']>1000 %}
    <p>Precio regular</p> 
    {% else %}
    <p>Precio oferta</p>
    {% endif %}

{% endblock %}

dev/4/flask_app/my_app/templates/product/update.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.update',id=product.id) }}" method="POST">
        {%include 'product/_form.html'%}

        <input class="btn btn-success" type="submit" value="Actualizar">
    </form>

{% endblock %}